require_relative "bargain_berths/printer/date_fare"
require_relative "bargain_berths/printer/fare"
require_relative "bargain_berths/coordinator"
require_relative "bargain_berths/counter"
require_relative "bargain_berths/fare"
require_relative "bargain_berths/page"
require_relative "bargain_berths/result_page"
